name: Clear GitHub Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const staleIssues = issues.data.filter(issue => {
              const createdAt = new Date(issue.created_at);
              const now = new Date();
              return (now - createdAt) > 1000 * 60 * 60 * 24 * 30; // 30 days old
            });

            for (const issue of staleIssues) {
              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
